feature - northstarcopack - new jenkins file for setting up wordpress server27

diff --git a/jenkins/newWordPressServer/Jenkinsfile b/jenkins/newWordPressServer/Jenkinsfile
--- a/jenkins/newWordPressServer/Jenkinsfile
+++ b/jenkins/newWordPressServer/Jenkinsfile
@@ -106,13 +106,9 @@ stage('Configure Nginx Reverse Proxy') {
     steps {
         script {
             sshagent(credentials: ['id_ed2_techvvs']) {
-            def document_root = 'document_root'
-            def astcgi_script_name = 'astcgi_script_name'
-
                 sh """
                     ssh -o StrictHostKeyChecking=no techvvs@${params.HOSTNAME} << 'EOF'
-                    if ! grep -q "${params.TENANT_NAME}${params.BASE_DOMAIN}" /etc/nginx/sites-available/default; then
-                        sudo bash -c 'cat > /etc/nginx/sites-available/default' << CONFIG
+                    sudo bash -c 'cat > /etc/nginx/sites-available/default' << "CONFIG"
 server {
     listen 80;
     server_name ${params.TENANT_NAME}${params.BASE_DOMAIN};
@@ -125,28 +121,26 @@ server {
         try_files \$uri \$uri/ /index.php;
     }
 
-    location ~ \\\\.php\\\$ {
+    location ~ \\.php\$ {
         include snippets/fastcgi-php.conf;
         fastcgi_pass unix:/var/run/php/php-fpm.sock;
-        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
+        fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
         include fastcgi_params;
     }
 
-    location ~ /\\\\.ht {
+    location ~ /\.ht {
         deny all;
     }
 }
 CONFIG
 
-                        if sudo nginx -t; then
-                            sudo systemctl reload nginx
-                            echo "Nginx configuration validated and reloaded."
-                        else
-                            echo "Nginx configuration test failed. Exiting."
-                            exit 1
-                        fi
+                    sudo nginx -t
+                    if [ $? -eq 0 ]; then
+                        sudo systemctl reload nginx
+                        echo "Nginx configuration validated and reloaded."
                     else
-                        echo "Nginx configuration already exists for ${params.TENANT_NAME}${params.BASE_DOMAIN}. Skipping."
+                        echo "Nginx configuration test failed. Exiting."
+                        exit 1
                     fi
 EOF
                 """
@@ -154,6 +148,7 @@ EOF
         }
     }
 }
+
 
 
 
